In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
from main.autoFIS.autoFIS.fuzzification import Fuzzification

In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [6]:
iris = datasets.load_iris()
df_iris = pd.DataFrame(iris['data'])
df_iris['target'] = iris['target']
X = iris['data']
y = iris['target']
X_train, X_test, y_train, y_test = train_test_split(X, y,  test_size=0.30, random_state=42)

In [8]:
fuzz2 = Fuzzification(X_train[:,[1]],triangle_format = 'tukey')
c = fuzz2.triangle_mb(y = X_train[:,[1]],triangle_format = 'tukey')

[2.  3.  4.2]


- fazer como transformer.
    - fit: 
           
           Pegar o X como parâmetro de entrada e setar x_min, x_max e centers.
           Para variáveis categóricas, só fazer o mapping do onehot

    - transform: 
    
           Aplicar a fuzzificação com os parametros do fit

In [179]:
list_categorical = np.array(['cats','cats','cats','cats','cats','cats','cats','dogs','dogs','dogs','dogs','dogs'])
list_categorical2 = np.array([0,1,0,1,0,1,1,1,0,1,0,0])
list_numerical = np.array([5,6,7,8,9,10,-1,-2,-3,-4,-5,-6])
class_target = np.array ([1,1,1,1,1,0,0,0,0,0,1,1])

In [180]:
X_sample = pd.DataFrame(data = {'att1':list_categorical,'att2':list_numerical,'att3':list_categorical2})

In [181]:
def tukey_centers(x,n_fuzzy_sets):
    return np.percentile(x, np.linspace(0, 100, n_fuzzy_sets).tolist())

def normal_centers(x_min,x_max,n_fuzzy_sets):
    return np.linspace(x_min, x_max, n_fuzzy_sets)

def build_fuzzy_sets():
     membership_far_left = self.trapmf(y, [-np.inf, -np.inf, center[0], center[1]])
        membership_far_right = self.trapmf(y, [center[n_fuzzy_sets - 2], center[n_fuzzy_sets - 1], np.inf, np.inf])

    fuzzy_sets = np.array(membership_far_left)
    for i in range(n_fuzzy_sets - 2):
        aux = self.trimf(y, center[i:i + n_fuzzy_sets])
        fuzzy_sets = np.append(fuzzy_sets, aux, 1)

    fuzzy_sets = np.append(fuzzy_sets, membership_far_right, 1)

    return fuzzy_sets

In [182]:
from sklearn.preprocessing import OneHotEncoder

In [183]:
categorical_attributes_mask = [True,False,True]
triangle_format = 'normal'
n_fuzzy_sets = 3

# fuzzify numerical
X_numerical = X_sample.loc[:,np.invert(categorical_attributes_mask)]

# fuzzify categorical
X_categorical = X_sample.loc[:,categorical_attributes_mask]

In [195]:
min_attributes = X_numerical.min()
max_attributes = X_numerical.max()

if triangle_format == 'tukey':
    centers = [tukey_centers(x,n_fuzzy_sets) for x in X_numerical.values.T]
else:
    centers = [normal_centers(mini,maxi,n_fuzzy_sets) for mini,maxi  in zip(min_attributes,max_attributes)]

In [196]:
# categories must be provided by the user. In case its empty, it will be calculated automatically (not optimal)
categories = [np.unique(x) for x in X_categorical.values.T]
categorical_encoder = OneHotEncoder(categories=categories).fit(X_categorical.values)
X_categorical_encoded = categorical_encoder.transform(X_categorical.values).toarray()

In [194]:
fuzz_dict_params = {
    'min': min_attributes,
    'max': max_attributes,
    'center': centers,
    'categorical':categorical
}

cols = X_sample.columns

fuzz_params = pd.DataFrame(fuzz_dict_params,index = cols)
fuzz_params

ValueError: Shape of passed values is (2, 4), indices imply (3, 4)

In [34]:
if triangle_format == 'tukey':
    center = np.percentile(y, np.linspace(0, 100, n_fuzzy_sets).tolist())
    # print(center)
else:
    ymin = min(y)
    ymax = max(y)
    center = np.linspace(ymin, ymax, n_fuzzy_sets)

array([-6.,  2., 10.])

In [26]:
# def triangle_mb(self,y, triangle_format = 'normal', n_membership_functions = 3):

        """
        Aplication of 'n' triangular membership functions
        
        Parameters:
            
            y: Attribute
            triangle_format: 'normal' or 'tukey'
            n_membership_functions: number of triangular membership functions
            
        Return: array with membership functions
        """

if triangle_format == 'tukey':
    center = np.percentile(y, np.linspace(0, 100, n_membership_functions).tolist())
    print(center)
else:
    ymin = min(y)
    ymax = max(y)
    center = np.linspace(ymin, ymax, n_membership_functions)

membership_far_left = self.trapmf(y, [-np.inf, -np.inf, center[0], center[1]])
membership_far_right = self.trapmf(y, [center[n_membership_functions - 2], center[n_membership_functions - 1], np.inf, np.inf])

fuzzy_sets = np.array(membership_far_left)
for i in range(n_membership_functions - 2):
    aux = self.trimf(y, center[i:i + n_membership_functions])
    fuzzy_sets = np.append(fuzzy_sets, aux, 1)

fuzzy_sets = np.append(fuzzy_sets, membership_far_right, 1)

return fuzzy_sets

[-6.  2. 10.]
